### ISSUE TITLE
SuperProductivity install fails

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [Xav83/chocolatey-packages#23]
after installing, windows tries to create some shortcuts but fails. The superproductivity exe is nowhere to be seen. If I install superproductivity manually though one of the EXEs from the github releases, it works fine

**Comment by hkdemiralp** [comment]
SuperProductivity install script tries to install arm executable instead of x64 windows.  $url64 variable is wrongly refers to "superProductivity-Setup-7.13.2-arm64.exe". In the package install file $url64 location needs to be corrected.

**Comment by mathisgauthey** [comment]
Still an issue today. Can't install the .exe directly as it is a portable version, the microsoft store is buggy if you keep the option to go to taskbar if closed.

I have this issue on both my windows 11 laptops.

**Comment by ItsIgnacioPortal** [comment]
> Can't install the .exe directly as it is a portable version

Make a folder for it in Program Files, move the exe there, and then make a shortcut for it and place it in the startup folder.

**Comment by mathisgauthey** [comment]
> > Can't install the .exe directly as it is a portable version
> 
> Make a folder for it in Program Files, move the exe there, and then make a shortcut for it and place it in the startup folder.

Oh sorry I might have explained myself poorly.

Yes it works this way, but if you pin the executable to the taskbar, it'll open another one when launching.
And if you open the one that launched afterward, it won't be able to open up on next boot because it was just a temp shortcut.

Hence the issue on my end ! But thanks, it'll help people 💪

**Comment by Xav83** [comment]
Hi everyone,

I have updated the package in order to correct the issue you mentioned.
It should be fixed since the package version `7.16.0.20231228` ([package link](https://community.chocolatey.org/packages/super-productivity/7.16.0.20231228)).

Feel free to test that out, when you will have the time and give me some feedback 😊
Have a nice day

**Comment by hkdemiralp** [comment]
Hi, @Xav83 ,
Thank you very much. Now, everything works correctly. On my Windows 11 x64 OS, SuperProductivity is updated successfully.

**Comment by mathisgauthey** [comment]
Can confirm, the installation works fine now. Finally, we can ditch the Microsoft Store version ! Thanks !

Can be closed I guess.

**Comment by mathisgauthey** [comment]
> Hi everyone,
> 
> I have updated the package in order to correct the issue you mentioned. It should be fixed since the package version `7.16.0.20231228` ([package link](https://community.chocolatey.org/packages/super-productivity/7.16.0.20231228)).
> 
> Feel free to test that out, when you will have the time and give me some feedback 😊 Have a nice day

Can confirm, the installation works fine now. Finally, we can ditch the Microsoft Store version ! Thanks !

Can be closed I guess.

EDIT : When you pin SupProd to the taskbar and have the `stay minimized to tray` option activated, if you close SupProd, you **can't open it back from the pinned taskbar icon**. You need to click on the tray icon.

**Comment by Xav83** [comment]
Thank you @hkdemiralp, @mathisgauthey for your feedback :slightly_smiling_face: 

> EDIT : When you pin SupProd to the taskbar and have the stay minimized to tray option activated, if you close SupProd, you can't open it back from the pinned taskbar icon. You need to click on the tray icon.

This issue may come from the SuperProductivity installer itself, since `Chocolatey` only runs the installer provided by @johannesjo, the software author of SuperProductivity. So you should probably report it on [super-productivity github repository](https://github.com/johannesjo/super-productivity/issues) :wink:
