### ISSUE TITLE
false checksum for sophia-package

### ISSUE THREAD

**Issue by dsan0815** [Xav83/chocolatey-packages#27]
Hi,
since sophia 6.5.1 the checksum in choco-package is broken.
currently for version 6.5.3
package-checksum: 9bae4d4c2fd9ded33dbf92b677c9027967e94774bf25b02dcdca90fe30444325
sophia-checksum: 95653FA8D7B48C33E09EBDBD52A5C2FFEB3A6816C1E6CE0E0A28B6CB3BB898B1
(from https://github.com/farag2/Sophia-Script-for-Windows/releases/download/6.5.3/SHA256SUM)
can you check this :)

**Comment by Xav83** [comment]
Hi @dsan0815,

First of all, thank you for reporting this issue and sorry about the answer's delay.

Indeed, the version `6.5.1` and `6.5.3` suffers from this issue.
This is triggered when the software authors modify the release's assets after the chocolatey package has been created.

From the version `6.5.4` to the version `6.5.9` (the newest one to date), there is no issue in that regard.
So I have unlisted the problematic versions, as people probably have already moved to a more recent version.
If some people really needs those specific version, then, I'll re-create them :wink: 

If that happens again, I'll hopefully notice your message sooner, in order to avoid this kind of "too-late-resolution" :smiling_face_with_tear:
