### ISSUE TITLE
(Crow Translator) Add a shim for crow.exe binary

### ISSUE THREAD

**Issue by Destroy666x** [Xav83/chocolatey-packages#28]
Add the binary to other binaries (`C:\ProgramData\chocolatey\bin`) as the application has CLI capabilities and it's not in `PATH` after installation right now.

**Comment by Xav83** [comment]
Hi @Destroy666x 🙂 

I have adapted the crow translater package source in order to generate the shim you requested after the installation (cf [commit df50da](https://github.com/Xav83/chocolatey-packages/commit/df50da3c53649754dff78f60a2f6c27d5ede29f4)).

Do you want me to generate a new version of the package with this new feature, or can you wait the next official release of Crow Translate ?
If you want, you also run the following command in your powershell commande to generate the shim on your computer:
```powershell
& "$env:ChocolateyInstall\tools\shimgen.exe" --output="$env:ChocolateyInstall\bin\crow.exe" --path="$env:Programfiles\Crow Translate\crow.exe"
```

**Comment by Destroy666x** [comment]
It's no priority and can wait for sure, thanks.

**Comment by Xav83** [comment]
Great ! I'll close this issue then :wink: 

PS: If you want to be notified when the new version of the Crow Translate will be available, I post about the new versions of the packages I maintain on my [Twitter / X](https://twitter.com/10xLearner).
