### ISSUE TITLE
(HidHide) install autorestarted my machine

### ISSUE THREAD

**Issue by Destroy666x** [Xav83/chocolatey-packages#29]
Which should 100% not be a thing for obvious reasons. Not sure if installer supports that, but it should.

**Comment by Xav83** [comment]
Hi @Destroy666x  :slightly_smiling_face: 

I reproduced your issue, it is indeed something to avoid.
I found a way to tell the installer how to not do that (cf. [7df4c3](https://github.com/Xav83/chocolatey-packages/commit/7df4c313612b485a2cbf0f7d9b9ee06241abb237)).

I am going to update the chocolatey package so that this fix will be available to everyone! I'll keep you posted :wink:

**Comment by Xav83** [comment]
Here in the [link to the new version of the package](https://community.chocolatey.org/packages/hidhide/1.4.192.20240121) with the fix 😉 
It is currently being in the review process of the Chocoatey team.

**Comment by Destroy666x** [comment]
Thanks!

**Comment by Xav83** [comment]
@Destroy666x This is done!  :slightly_smiling_face: 

The [new version of the package hidhide](https://community.chocolatey.org/packages/hidhide) without this issue is now available. :tada:
