### ISSUE TITLE
choco install bizhawk downloads Linux version

### ISSUE THREAD

**Issue by Patrick-1994-** [Xav83/chocolatey-packages#4]
I suppose the problem is here:
https://github.com/Xav83/chocolatey-packages/blob/70cadbd22c0aa59dd909e925655a79cad78134fa/automatic/bizhawk/update.ps1#L18
The linux download is apparently relatively new.
Edit: Well, rather, here:
`$re  = "BizHawk-.+.zip$"`

this works:
PS C:\Users\patri> $re  = "BizHawk-.+win.+.zip$"
PS C:\Users\patri> $download_page.links | ? href -match $re  | Select -First 1 -expand href
/TASVideos/BizHawk/releases/download/2.6.1/BizHawk-2.6.1-win-x64.zip

**Comment by Xav83** [comment]
Thank you @Patrick-1994- for this issue, and for the solution you proposed 🙂👍

I am going to look at it either today or tomorrow (depending on when I will have the time), and come back to you once I will have tested the Bizawk chocolatey package on my machine.

**Comment by Xav83** [comment]
@Patrick-1994- Indeed, I looked at the correction you proposed and, your solution is right 🙂👍 

I have pushed the solution on the [develop branch](https://github.com/Xav83/chocolatey-packages/commit/fc76b1830471ee4607d843b8e56d81bbc768fb9e), so that the next release of BitHawk will have the right package attached to it in Chocolatey.

For now, the [Chocolatey package available on Chocolatey server](https://chocolatey.org/packages/bizhawk) is still the linux one.
I am going to check how I can correct that.

I'll get back to you when I will have some more information about that 😉

**Comment by Xav83** [comment]
Hi again @Patrick-1994- ! 🙂 

I have been experimenting with Chocolatey and [AU](https://github.com/majkinetor/au) to push the [BizHawk package](https://chocolatey.org/packages/bizhawk) again even if a package of the same version already exists on Chocolatey server, and I finally succeed to do it 🍾 
At the moment the package is passing through the validation of Chocolatey, and you can follow it [here](https://chocolatey.org/packages/bizhawk/2.6.1.20210301).

Hopefully everything will be right and a working package will be soon accessible to everyone 😉

**Comment by Xav83** [comment]
@Patrick-1994-

The [Chocolatey package of Bizhawk](https://chocolatey.org/packages/bizhawk) has been update and should now contain the right executable for Windows !

If you have any trouble with this new package, do not hesitate to notify me about it 😉 
And if everything works fine with this new package on your machine, you can also update this issue, so that I can close it, and validate that it works again, for everyone 🙂

**Comment by Patrick-1994-** [comment]
Fixed, thanks.

Extracting C:\Users\patri\AppData\Local\Temp\chocolatey\bizhawk\2.6.1.20210301\BizHawk-2.6.1-win-x64.zip to C:\ProgramData\chocolatey\lib\bizhawk\tools...
C:\ProgramData\chocolatey\lib\bizhawk\tools
 ShimGen has successfully created a shim for DiscoHawk.exe
 ShimGen has successfully created a shim for EmuHawk.exe
 The install of bizhawk was successful.
  Software installed to 'C:\ProgramData\chocolatey\lib\bizhawk\tools'
